# A sample TOML config file.
enabled_env = "development"
[development]
server = "192.168.1.1"
port = 8080
connection_max = 100
    [development.db]
    host = "localhost" 
    port = 5432 
    user = "postgres" 
    dbname = "devdb" 
    password = "123456" 
    sslmode = "disable"

[staging]
server = "192.168.1.2"
port = 8090
connection_max = 200
    [staging.db]
    host = "staging" 
    port = 5432 
    user = "postgres" 
    dbname = "stagedb" 
    password = 123456 
    sslmode = "disable"

[production]
server = "192.168.1.3"
port = 9000
connection_max = 5000
    [production.db]
    host = "prodserver" 
    port = 5432 
    user = "postgres" 
    dbname = "proddb" 
    password = 123456 
    sslmode = "disable"
